[bugfix] Fix: Use DDP for PPO traning will cause AttributeError: 'DistributedDataParallel' object has no attribute 'config' error (#5822)
* fix: unwrap model for ppo trainer in _save_checkpoint

* Update swift/trainers/rlhf_trainer/ppo_trainer.py

use more robust error check

Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>

* lint: reformat ppo trainer

---------

Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>